version: 0.4.6

namespace: tazaker
project: tazaker-nats

services:
  - name: nats
    image: nats-streaming
    tag: latest
    args:
      [
        "-p",
        "4222",
        "-m",
        "8222",
        "-hbi",
        "5s",
        "-hbt",
        "5s",
        "-hbf",
        "2",
        "-SD",
        "-cid",
        "tazaker",
      ]
    ports:
      - name: client
        port: 4222
      - name: monitoring
        port: 8222
