apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  ENVIRONMENT: production
  STRIPE_PUBLISHABLE_KEY: pk_live_51OXSmaHxxGduf7hI1BhoX0R1e6mQtCN5jxnM12bWXNE3tU5ZhnSh96PJD7ZrqCCH2vhThBwXh9nQvht5DDqk3FN700uhNoRdhY
