version: "3.8"

services:
  mailserver:
    image: analogic/poste.io
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data:/data
    hostname: mail.tazaker.org
    restart: always
