apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: markmorcos/tazaker-identity
          envFrom:
            - configMapRef:
                name: global-config
          env:
            - name: MONGO_URI
              value: "mongodb://identity-mongo-srv:27017/identity"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLIENT_ID
              value: tazaker
            - name: NATS_URL
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-srv
spec:
  selector:
    app: identity
  ports:
    - name: identity
      protocol: TCP
      port: 3000
      targetPort: 3000
