apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: markmorcos/tazaker-notification
          env:
            - name: NATS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLIENT_ID
              value: tazaker
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: SENDGRID_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid-secret
                  key: SENDGRID_KEY
