apiVersion: apps/v1
kind: Deployment
metadata:
  name: payouts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payouts
  template:
    metadata:
      labels:
        app: payouts
    spec:
      containers:
        - name: payouts
          image: markmorcos/tazaker-payouts
          envFrom:
            - configMapRef:
                name: global-config
          env:
            - name: MONGO_URI
              value: "mongodb://payouts-mongo-srv:27017/payouts"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLIENT_ID
              value: tazaker
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: paypal-secret
                  key: PAYPAL_CLIENT_ID
            - name: PAYPAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: paypal-secret
                  key: PAYPAL_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: payouts-srv
spec:
  selector:
    app: payouts
  ports:
    - name: payouts
      protocol: TCP
      port: 3000
      targetPort: 3000
