apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v2-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-v2
  template:
    metadata:
      labels:
        app: web-v2
    spec:
      containers:
        - name: web-v2
          image: markmorcos/tazaker-web-v2
          envFrom:
            - configMapRef:
                name: global-config
---
apiVersion: v1
kind: Service
metadata:
  name: web-v2-srv
spec:
  selector:
    app: web-v2
  ports:
    - name: web-v2
      protocol: TCP
      port: 3000
      targetPort: 3000
