chartVersion: 0.3.0

project:
  name: "tazaker"

repository:
  name: "markmorcos/tazaker"
  path: "./identity"

ingress:
  host: tazaker.morcos.tech
  rules:
    - host: tazaker.morcos.tech
      path: /api/(auth|users)/?(.*)
      pathType: ImplementationSpecific
      serviceName: identity-service

deployments:
  - name: identity-deployment
    image: markmorcos/tazaker-identity

services:
  - name: identity-service
    port: 3000
