name: expiration

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "expiration/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: cd expiration && docker build . -f Dockerfile.production -t markmorcos/tazaker-expiration
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push markmorcos/tazaker-expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save tazaker
      - run: kubectl rollout restart deployment expiration-depl
