name: manifest

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save tazaker
      - run: kubectl apply -f infra/common/init,infra/production/init -R --wait
      - run: kubectl apply -f infra/common/k8s,infra/production/k8s -R --wait
