name: manifest

on:
  workflow_dispatch:
    branches:
      - main
      - staging
  push:
    branches:
      - main
      - staging
    paths:
      - "infra/**"

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v4
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save tazaker
      - run: kubectl apply -f infra/common/init,infra/staging/init -R
      - run: kubectl apply -f infra/common/k8s,infra/staging/k8s -R

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save tazaker
      - run: kubectl apply -f infra/common/init,infra/production/init -R
      - run: kubectl apply -f infra/common/k8s,infra/production/k8s -R
